server:
  port: 8082
  servlet:
    context-path: /janvier
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/janvier_db?useUnicode=true&characterEncoding=UTF-8}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Ilies2004_}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
      encoding: UTF-8
  
  messages:
    encoding: UTF-8
    basename: messages

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

paypal:
  client-id: ${PAYPAL_CLIENT_ID:ASXWWhLhd_mx15AtVETBFrxq-4KsZicGJnon4ppqKqapddF8Ugkov7T4zRZNhtCWm5-szWaVu3Sj3ive}
  client-secret: ${PAYPAL_CLIENT_SECRET:EKXVHcJ9TfPvJn08uuhEQZEkviCVHL7OXLK0YFRkUDNg1ozIXjL_yKlB6GWPXo99QzgMDvP_OBLcVjnr}
  mode: ${PAYPAL_MODE:sandbox}
